# Generated by Django 5.2.17 on 2026-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_remove_admin_password_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
