# Generated by Django 5.2.17 on 2026-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_rename_payment_method_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mode',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True),
        ),
    ]
