# Generated by Django 5.2.17 on 2026-09-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_payment_course_payment_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='tables.course'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='study_material'),
        ),
    ]
