# Generated by Django 5.2.17 on 2026-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_batch_mode_alter_batch_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], default='Online', max_length=20),
        ),
    ]
